# Generated by Django 2.0.5 on 2018-06-01 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ethereum_events', '0003_auto_20180531_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=256)),
                ('transaction_hash', models.CharField(max_length=66, validators=[django.core.validators.MinLengthValidator(66)])),
                ('transaction_index', models.IntegerField()),
                ('block_hash', models.CharField(max_length=66, validators=[django.core.validators.MinLengthValidator(66)])),
                ('block_number', models.IntegerField()),
                ('log_index', models.IntegerField()),
                ('address', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)])),
                ('args', models.TextField(default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('monitored_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_events', to='django_ethereum_events.MonitoredEvent')),
            ],
            options={
                'verbose_name_plural': 'Failed to process Events',
                'verbose_name': 'Failed to process Event',
            },
        ),
    ]
